ARG CONFIG_DIR=tests/_docker
ARG APACHE_RUN_USER
ARG APACHE_RUN_GROUP
ARG WP_RELEASE latest
ARG E20R_HOST_IP

FROM wordpress:${WP_RELEASE}

RUN docker-php-ext-install pdo_mysql && \
    pecl install pcov && docker-php-ext-enable pcov && \
    pecl install xdebug && docker-php-ext-enable xdebug
COPY ${CONFIG_DIR}/docker-*.ini /usr/local/etc/php/conf.d

# RUN pecl install runkit && docker-php-ext-enable runkit
