name: Build I18N files for repository

# This is used to test changes to the test/build/deploy workflow for the plugin so only applies if the
# branch is named test_workflow<something>
on:
  push:
    branches:
     - refs/heads/*
     - !main
     - !master

jobs:
  plugin_tests:
    strategy:
      matrix:
        php_version: [ '7.4', '8.0', '8.1' ]
    name: "Plugin tests - PHP"
    defaults:
      run:
        shell: bash
    env:
      E20R_PLUGIN_NAME: pmpro-import-members-from-csv
      GITHUB_TOKEN: ${{ secrets.GITHUB }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      CONTAINER_ACCESS_TOKEN: ${{ secrets.CONTAINER_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: eighty20results/pmpro-import-members-from-csv

      - name: Setup PHP with Composer V2+
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: mbstring, xdebug
          tools: composer:v2
          coverage: pcov

      - name: Login to Docker HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.CONTAINER_ACCESS_TOKEN }}

      - name: Load cached Composer and test related dependencies
        uses: actions/cache@v3
        id: composer-cache
        with:
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-cache
          path: inc/**

      - name: Install all needed dependencies for Composer
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: make composer-dev

      - name: Install all needed WordPress plugin dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: make wp-deps

      - name: Install all needed dependencies for Docker
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: make docker-deps

      - name: Run all Standard Tests
        run: make tests

      - name: Download artifacts
        uses: actions/download-artifact@v3

  build_i18n:
    name: Build the I18N translation files
    needs: plugin_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: eighty20results/pmpro-import-members-from-csv

      - name: WordPress .pot File Generator for e20r-members-list
        uses: iamdharmesh/action-wordpress-pot-generator@v1
        with:
          destination_path: './languages'
          slug: ${{ env.E20R_PLUGIN_NAME }}
          text_domain: ${{ env.E20R_PLUGIN_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
