name: Run Unit Tests when creating a PR

# Run Unit Test when new PR is created
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Execute tests when creating a PR
  pr_tests:
    name: Pull Request related testing
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with Composer V2+
        uses: shivammathur/setup-php@v2
        with:
          php-version: [ '7.4', '8.0' ]
          extensions: mbstring, xdebug
          tools: composer:v2
          coverage: pcov
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: eighty20results/pmpro-import-members-from-csv
      - name: Run Code Standard Tests
        run: make code-standard-test
      - name: Run PHP Stan Tests
        run: make phpstan-test
      - name: Run the unit tests
        run: make unit-test

  update_tests:
    name: Test on push
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with Composer V2+
        uses: shivammathur/setup-php@v2
        with:
          php-version: [ '7.4', '8.0' ]
          extensions: mbstring, xdebug
          tools: composer:v2
          coverage: pcov
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: eighty20results/pmpro-import-members-from-csv
      - name: Run Code Standard Tests
        run: make code-standard-test
      - name: Run PHP Stan Tests
        run: make phpstan-test
      - name: Run the unit tests
        run: make unit-test
