name: Release to wordpress.org

on:
  # Deploy when a new release is created
  release:
    # Only deploy when the admin creates/publishes/edits/pre-releases from GitHub
    types: [edited, published]
    branches:
      - main

jobs:
  # To push the release (sources) to the WordPress.org SVN instance for this plugin
  wordpress:
    name: Push plugin to wordpress.org
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with Composer V2+
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring
          tools: composer:v2
          ini-values: xdebug.mode=coverage
          coverage: pcov
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: eighty20results/pmpro-import-members-from-csv
          ref: main
      - name: Run the unit tests
        run: |
          ln -s $(which composer) ./composer.phar
          make unit-test
      - name: WordPress Plugin Deployment for ${{ github.ref }}
        uses: eighty20results/pmpro-import-members-from-csv@main
        env:
          SLUG: pmpro-import-members-from-csv
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
