name: Test of "Release to wordpress.org" workflows

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - test_workflow*

jobs:
  # To push the release (sources) to the WordPress.org SVN instance for this plugin
  wordpress:
    name: Test of "Push to wordpress.org" workflow
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with Composer V2+
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring
          tools: composer:v2
          ini-values: xdebug.mode=coverage
          coverage: pcov

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: eighty20results/pmpro-import-members-from-csv
          ref: test_workflow_updates

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.CONTAINER_ACCESS_TOKEN }}

      - name: Run the plugin tests
        run: make test
        env:
          E20R_PLUGIN_NAME: 00-e20r-utilities
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          CONTAINER_ACCESS_TOKEN: ${{ secrets.CONTAINER_ACCESS_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}

      - name: Test of "WordPress Plugin Deploy" for ${{ github.ref }}
        uses: eighty20results/pmpro-import-members-from-csv@test_workflow_updates
        env:
          SLUG: pmpro-import-members-from-csv
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          CONTAINER_ACCESS_TOKEN: ${{ secrets.CONTAINER_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
